### ISSUE TITLE
Access without permission renders 500

### ISSUE THREAD

**Issue by MrSerth** [openHPI/codeharbor#245]
When accessing `/admin` without being logged in, I encounter an HTTP 500 error. However, I would prefer being redirected to another page and getting a flash message about that.

---

Sentry Issue: [CODEHARBOR-4]

```
CanCan::AccessDenied: You are not authorized to access this page.
  cancan/ability.rb:180:in `authorize!'
    raise AccessDenied.new(message, action, subject, args)
  rails_admin/extensions/cancancan/authorization_adapter.rb:19:in `initialize'
    @controller.current_ability.authorize! :access, :rails_admin
  rails_admin/config.rb:160:in `new'
    @authorization_adapter = klass.new(*([self] + args).compact)
  rails_admin/config.rb:160:in `block in authorize_with'
    @authorization_adapter = klass.new(*([self] + args).compact)
  rails_admin/application_controller.rb:56:in `instance_eval'
    instance_eval(&RailsAdmin::Config.authorize_with)
...
(102 additional frame(s) were not displayed)
```

**Comment by kkoehn** [comment]
Should be fixed now. Accidentally pushed it to master directly

**Comment by MrSerth** [comment]
No problem. And many thanks! I deployed the code and tested it ;)
