### ISSUE TITLE
ProFromA Import fails with nested tasks

### ISSUE THREAD

**Issue by MrSerth** [openHPI/codeharbor#441]
Sentry Issue: CODEHARBOR-K

```
NoMethodError: undefined method `[]' for nil:NilClass
  app/services/proforma_service/task_from_cached_file.rb:15:in `execute'
    task = import_tasks.find { |task_hash| task_hash[:path] == subfile.with_indifferent_access[:path] }[:task]
  app/services/service_base.rb:5:in `call'
    new(*args).execute
  app/controllers/exercises_controller.rb:247:in `import_exercise_confirm'
    task = ProformaService::TaskFromCachedFile.call(import_exercise_confirm_params.to_hash.symbolize_keys)
...
(92 additional frame(s) were not displayed)
```

**Comment by kkoehn** [comment]
I can't reproduce this.
Importing a zip with multiple task-zips works on production
