### ISSUE TITLE
Task download fails after ActiveStorage migration

### ISSUE THREAD

**Issue by MrSerth** [openHPI/codeharbor#457]
This is the issue we faced today. If it is a temporary problem, I would propose not to fix it.

Sentry Issue: [CODEHARBOR-M]

```
Errno::ENOENT: No such file or directory @ rb_sysopen - <full path>/storage/vr/ww/vrww7x80sah8vpihf1flu3l1lwn8
  activestorage (6.0.3.4) lib/active_storage/service/disk_service.rb:134:in `initialize'
  activestorage (6.0.3.4) lib/active_storage/service/disk_service.rb:134:in `open'
  activestorage (6.0.3.4) lib/active_storage/service/disk_service.rb:134:in `stream'
  activestorage (6.0.3.4) lib/active_storage/service/disk_service.rb:28:in `block in download'
  activesupport (6.0.3.4) lib/active_support/notifications.rb:180:in `block in instrument'
...
(107 additional frame(s) were not displayed)

ActiveStorage::FileNotFoundError: ActiveStorage::FileNotFoundError
  activestorage (6.0.3.4) lib/active_storage/service/disk_service.rb:140:in `rescue in stream'
  activestorage (6.0.3.4) lib/active_storage/service/disk_service.rb:133:in `stream'
  activestorage (6.0.3.4) lib/active_storage/service/disk_service.rb:28:in `block in download'
  activesupport (6.0.3.4) lib/active_support/notifications.rb:180:in `block in instrument'
  activesupport (6.0.3.4) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
...
(106 additional frame(s) were not displayed)
```

**Comment by kkoehn** [comment]
I tried uploading and downloading a file in production and it worked. Maybe this specific file got lost in a migration.
